#!/bin/sh

# 配合 luci-nginx，默认启用 HTTPS（自签证书，80 端口跳转 443）
[ -f /etc/config/nginx ] || exit 0

uci -q set nginx.global.uci_enable='true'
uci -q set nginx._lan.uci_manage_ssl='self-signed'
uci -q commit nginx

exit 0
