#!/bin/sh

# 配合 luci-nginx，默认启用 HTTPS（自签证书，80 端口跳转 443）
[ -f /etc/config/nginx ] || exit 0

# 启用 nginx-util 生成 UCI 配置
uci -q set nginx.global.uci_enable='true'

# 强制 _lan 监听 443（兼容从旧配置保留/升级上来的固件）
uci -q set nginx._lan=server
uci -q delete nginx._lan.listen
uci -q add_list nginx._lan.listen='443 ssl default_server'
uci -q add_list nginx._lan.listen='[::]:443 ssl default_server'
uci -q set nginx._lan.uci_manage_ssl='self-signed'
uci -q set nginx._lan.ssl_certificate='/etc/nginx/conf.d/_lan.crt'
uci -q set nginx._lan.ssl_certificate_key='/etc/nginx/conf.d/_lan.key'

# 确保存在 80 -> 443 跳转
uci -q set nginx._redirect2ssl=server
uci -q delete nginx._redirect2ssl.listen
uci -q add_list nginx._redirect2ssl.listen='80'
uci -q add_list nginx._redirect2ssl.listen='[::]:80'
uci -q set nginx._redirect2ssl.server_name='_redirect2ssl'
uci -q set nginx._redirect2ssl.return='302 https://$host$request_uri'

uci -q commit nginx

exit 0
